repos:
  - repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.1
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: commitlint
        name: Commit Lint
        entry: commitlint lint --message
        stages: [commit-msg]
        language: system
        description: "Commit Lint to Conventional Commits pattern"
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        stages: [pre-commit]
        language: system
        pass_filenames: false
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        types: [go]
        stages: [pre-commit]
        language: system
        pass_filenames: false
      - id: govulncheck
        name: govulncheck
        entry: govulncheck
        files: ^go\.mod$|^go\.sum$
        stages: [pre-commit]
        language: system
        pass_filenames: false
      - id: go-test
        name: go test
        entry: go test ./...
        types: [go]
        stages: [pre-commit]
        language: system
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --fix
        types: [go]
        stages: [pre-commit]
        language: system
        pass_filenames: false
        description: "Run golangci-lint only on go files staged on this commit"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      - id: check-toml
      - id: check-json
